server.port=8081
spring.application.name=budgetwise-expense-tracker

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/budgetwise?connectTimeoutMS=5000&socketTimeoutMS=5000
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=BudgetWiseSecretKeyForJWTAu5ThenticationWith256BitKeyLength123
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.budgetwise=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.web.access.intercept.FilterSecurityInterceptor=TRACE
